version: '3.8'

services:
  codexgui:
    build: .
    container_name: codexgui
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      # Mount the project directory to access Git repositories
      - ${PROJECTS_PATH:-~/projects}:/projects
    environment:
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=8000
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
      - CORS_ORIGINS=http://localhost:8000
      - DATA_DIR=/app/data
      - LOGS_DIR=/app/data/logs
      - SNAPSHOTS_DIR=/app/data/snapshots
      - DB_FILE=/app/data/codexgui.db
      - STATIC_FILES_DIR=/app/frontend/dist
    restart: unless-stopped
