import React from 'react';

// 임시 더미 컴포넌트 (Codex가 생성하지 않을 경우 보여질 화면)
const AgentConsole: React.FC = () => {
  return (
    <div style={{
      border: '1px solid #ccc',
      borderRadius: '4px',
      padding: '1rem',
      margin: '1rem 0',
      background: '#f8f8f8'
    }}>
      <h2>Agent Console (Under Development)</h2>
      <p>This component will be generated by Codex CLI.</p>
      <p>Please run the complete CodexGUI script to see the real component.</p>
    </div>
  );
};

export default AgentConsole;